In [0]:
import numpy as np
#import nltk
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import f1_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
import seaborn as sns
import string

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import pandas as pd
import json
import csv
yelp = []
for line in open('/content/gdrive/My Drive/255-yelp-assignment1/review_top50000.json', 'r'):
    yelp.append(json.loads(line))


In [5]:
df = pd.DataFrame(yelp)
df

business_id  cool                 date  funny  \
0      ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1      NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2      WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3      ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4      b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   
5      eU_713ec6fTGNO4BegRaww     0  2013-01-20 13:25:59      0   
6      3fw2X5bZYeW9xCz_zGhOHg     5  2016-05-07 01:21:02      4   
7      zvO-PJCpNk4fgAVUnExYAA     1  2010-10-05 19:12:35      1   
8      b2jN2mm9Wf3RcrZCgfo1cg     0  2015-01-18 14:04:18      0   
9      oxwGyA17NL6c5t1Etg5WgQ     1  2012-02-29 21:52:43      0   
10     8mIrX_LrOnAqWsB5JrOojQ     0  2011-11-30 02:11:15      0   
11     mRUVMJkUGxrByzMQ2MuOpA     0  2017-12-15 23:27:08      1   
12     FxLfqxdYPA6Z85PFKaqLrg     0  2016-05-07 01:36:53      0   
13     LUN6swQYa4xJKaM_UEUOEw     0  2018-04-27 20:25:26      0   
14     AakkkTuGZA2KBodKi2_u8A     0  2012-07-16 00:37:14      1   
15     YvrylyuWgbP90RgMqZQVnQ     0  2017-04-07 21:27:49      0   
16     NyLYY8q1-H3hfsTwuwLPCg     0  2015-01-03 22:47:34      0   
17     cHdJXLlKNWixBXpDwEGb_A     1  2015-04-01 16:30:00      7   
18     6lj2BJ4tJeu7db5asGHQ4w     0  2017-05-26 01:23:19      0   
19     y-Iw6dZflNix4BdwIyTNGA     0  2014-06-27 21:19:23      0   
20     qx6WhZ42eDKmBchZDax4dQ     0  2017-03-27 01:14:37      0   
21     Mem13A3C202RzT53npn4NA     9  2017-05-13 10:41:43      6   
22     I4Nr-MVc26qWr08-S3Q1ow     0  2016-01-17 05:26:22      0   
23     d_L-rfS1vT3JMzgCUGtiow     0  2016-07-25 03:57:19      0   
24     Sfc8Haz2Yri8Mo1L0E0TsA     0  2012-11-06 03:41:43      0   
25     FQ1wBQb3aNeRMThSQEV0Qg     0  2013-12-07 02:32:45      0   
26     hd5xm20tfSa70-6UqD9-bg     1  2014-08-10 22:07:35      1   
27     Gyrez6K8f1AyR7dzW9fvAw     1  2013-12-28 22:28:08      0   
28     9nTF596jDvBBia2EXXiOOg     0  2014-04-19 15:03:17      0   
29     SNL64axQhCO6Z7ohcWg3wA     0  2017-02-09 03:43:25      0   
...                       ...   ...                  ...    ...   
49970  dctnu1Ot3vE4V-GN8nNnKA     1  2017-03-04 18:28:15      0   
49971  jubHvev4-PO1PBNHFD73vw     0  2016-08-04 22:53:03      0   
49972  tzjUW8uffmsWcdkEe48Bmg     0  2018-04-28 16:29:13      0   
49973  uxYCZZGTuPK8TjXKkH7jCQ     0  2014-12-19 15:31:48      0   
49974  q7f_lCOKf40idrVSzmoYug     1  2018-03-04 13:19:56      0   
49975  TCoBE_BkDRrK0bWrh5VueQ     2  2017-06-07 23:07:25      4   
49976  r-s-G1yyETRzTALYG9js8A     3  2010-08-23 19:26:49      4   
49977  j9bWpCRwpDVfwVT_V85qeA     0  2014-02-07 03:54:42      0   
49978  -bd4BQcl1ekgo7avaFngIw     0  2018-05-20 01:21:45      0   
49979  W9JHcg3YTWo2-gfLSS4Wlw     0  2017-03-15 04:46:40      0   
49980  faPVqws-x-5k2CQKDNtHxw     1  2017-11-06 20:53:40      0   
49981  M51gw2cz_vXarNBLbKkOxQ     2  2012-07-16 18:47:31      0   
49982  QNiMs-AacTuOJwQAjmkrVA     0  2018-07-08 01:27:31      0   
49983  8WBHKj2davW6hhZWlUQ7DA     0  2017-01-15 03:55:48      0   
49984  xRzr_FDV5S6by9ieeSX8Cw     0  2018-08-14 05:12:20      0   
49985  lKC4TcCzszmd-2Ak2GCH5A     0  2017-04-19 17:50:07      0   
49986  ujHiaprwCQ5ewziu0Vi9rw     2  2016-08-04 07:25:52      2   
49987  KiE81YHZCEdPPlmrXghgzA     0  2018-02-11 11:45:10      0   
49988  vrKcFQPxj1Zzyj93yl-t6g     0  2017-01-02 15:22:53      0   
49989  mPk43gs2O2n06MNR-uDKfg     0  2015-04-01 21:21:51      0   
49990  FGWc5hjTaOql-Rut_bEbVw     4  2017-12-16 15:58:13      3   
49991  F73T-N5lRNL2Gcpg0Q4KKw     0  2017-03-04 04:16:30      0   
49992  5ZzmZjt5-5fsX03BL70DgA     0  2015-07-04 05:19:50      0   
49993  AfEOC5LlBeMt708QEQUihw     2  2013-06-24 23:00:55      3   
49994  nrahyQyopCtajDqUtVVVfA     0  2018-08-05 02:03:58      0   
49995  RJdSwvgAd2TRdQw4iOsrag     0  2015-10-08 03:24:48      0   
49996  coGEHGuUtnABP7KHgGlmRg     0  2018-08-05 02:47:25      0   
49997  OHwVDLnpNApygH-tdR8UNg     1  2013-05-08 01:58:00      0  

In [6]:
## convert text to lower case
df.text = df.text.str.lower()

## remove unnecessary punctuation
df['removed_punct_text']= df.text.str.replace('\n',''). \
                                          str.replace('[!"#$%&\()*+,-./:;<=>?@[\\]^_`{|}~]','')
df.head()

business_id  cool                 date  funny  \
0  ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1  NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2  WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3  ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4  b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   

                review_id  stars  \
0  Q1sbwvVQXV2734tPgoKj4Q    1.0   
1  GJXCdrto3ASJOqKeVWPi6Q    5.0   
2  2TzJjDVDEuAW6MR5Vuc1ug    5.0   
3  yi0R0Ugj_xUx_Nek0-_Qig    5.0   
4  11a8sVPMUFtaC7_ABRkmtw    1.0   

                                                text  useful  \
0  total bill for this horrible service? over $8g...       6   
1  i *adore* travis at the hard rock's new kelly ...       0   
2  i have to say that this office really has it t...       3   
3  went in for a lunch. steak sandwich was delici...       0   
4  today was my second out of three sessions i ha...       7   

                  user_id                                 removed_punct_text  
0  hG7b0MtEbXx5QzbzE6C_VA  total bill for this horrible service over 8gs ...  
1  yXQM5uF2jS6es16SJzNHfg  i adore travis at the hard rock's new kelly ca...  
2  n6-Gk65cPZL6Uz8qRm3NYw  i have to say that this office really has it t...  
3  dacAIZ6fTM6mqwW5uxkskg  went in for a lunch steak sandwich was delicio...  
4  ssoyf2_x0EQMed6fgHeMyQ  today was my second out of three sessions i ha...

In [30]:
positive_words=["good","great","love","best","fantastic","healthiest","definitely","authentic","professional","knowledgeable","confident","polite","friendly","free","wifi","pretty","priceless","privilege","prompt","awesome"]
negative_words=["horrible","slow","irritation","disappointed","awful","abruptly","ashamed","awful"]
neutral_words=["fine","average","ok","satisfy","overall","unfortunately","much","wont","just","worth","still", "though"]
mergedlist = positive_words + negative_words+neutral_words
print(mergedlist)

['good', 'great', 'love', 'best', 'fantastic', 'healthiest', 'definitely', 'authentic', 'professional', 'knowledgeable', 'confident', 'polite', 'friendly', 'free', 'wifi', 'pretty', 'priceless', 'privilege', 'prompt', 'awesome', 'horrible', 'slow', 'irritation', 'disappointed', 'awful', 'abruptly', 'ashamed', 'awful', 'fine', 'average', 'ok', 'satisfy', 'overall', 'unfortunately', 'much', 'wont', 'just', 'worth', 'still', 'though']


In [31]:
#reviews = "good yes"
import nltk
nltk.download('punkt')
Cust = []
from nltk.tokenize import sent_tokenize, word_tokenize
for r in df['text']: # counter for month indices
    review = word_tokenize(r)
    pos = 0
    neg = 0
    neu = 0
    for word in review:
        if word in mergedlist:
            if word in positive_words:
             pos = pos+1
            elif word in negative_words:
             neg = neg+1
            elif word in neutral_words:
             neu = neu +1
    #monthly_mean.append(s/n)
    if pos >= neg and pos >= neu:
     Cust.append('Positive')
    elif neg >= neu:
     Cust.append('Negative')
    else:
     Cust.append('Neutral') 
#print(pos)
#print(neg)
df['Predicted_review'] = Cust 
df

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


business_id  cool                 date  funny  \
0      ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1      NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2      WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3      ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4      b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   
5      eU_713ec6fTGNO4BegRaww     0  2013-01-20 13:25:59      0   
6      3fw2X5bZYeW9xCz_zGhOHg     5  2016-05-07 01:21:02      4   
7      zvO-PJCpNk4fgAVUnExYAA     1  2010-10-05 19:12:35      1   
8      b2jN2mm9Wf3RcrZCgfo1cg     0  2015-01-18 14:04:18      0   
9      oxwGyA17NL6c5t1Etg5WgQ     1  2012-02-29 21:52:43      0   
10     8mIrX_LrOnAqWsB5JrOojQ     0  2011-11-30 02:11:15      0   
11     mRUVMJkUGxrByzMQ2MuOpA     0  2017-12-15 23:27:08      1   
12     FxLfqxdYPA6Z85PFKaqLrg     0  2016-05-07 01:36:53      0   
13     LUN6swQYa4xJKaM_UEUOEw     0  2018-04-27 20:25:26      0   
14     AakkkTuGZA2KBodKi2_u8A     0  2012-07-16 00:37:14      1   
15     YvrylyuWgbP90RgMqZQVnQ     0  2017-04-07 21:27:49      0   
16     NyLYY8q1-H3hfsTwuwLPCg     0  2015-01-03 22:47:34      0   
17     cHdJXLlKNWixBXpDwEGb_A     1  2015-04-01 16:30:00      7   
18     6lj2BJ4tJeu7db5asGHQ4w     0  2017-05-26 01:23:19      0   
19     y-Iw6dZflNix4BdwIyTNGA     0  2014-06-27 21:19:23      0   
20     qx6WhZ42eDKmBchZDax4dQ     0  2017-03-27 01:14:37      0   
21     Mem13A3C202RzT53npn4NA     9  2017-05-13 10:41:43      6   
22     I4Nr-MVc26qWr08-S3Q1ow     0  2016-01-17 05:26:22      0   
23     d_L-rfS1vT3JMzgCUGtiow     0  2016-07-25 03:57:19      0   
24     Sfc8Haz2Yri8Mo1L0E0TsA     0  2012-11-06 03:41:43      0   
25     FQ1wBQb3aNeRMThSQEV0Qg     0  2013-12-07 02:32:45      0   
26     hd5xm20tfSa70-6UqD9-bg     1  2014-08-10 22:07:35      1   
27     Gyrez6K8f1AyR7dzW9fvAw     1  2013-12-28 22:28:08      0   
28     9nTF596jDvBBia2EXXiOOg     0  2014-04-19 15:03:17      0   
29     SNL64axQhCO6Z7ohcWg3wA     0  2017-02-09 03:43:25      0   
...                       ...   ...                  ...    ...   
49970  dctnu1Ot3vE4V-GN8nNnKA     1  2017-03-04 18:28:15      0   
49971  jubHvev4-PO1PBNHFD73vw     0  2016-08-04 22:53:03      0   
49972  tzjUW8uffmsWcdkEe48Bmg     0  2018-04-28 16:29:13      0   
49973  uxYCZZGTuPK8TjXKkH7jCQ     0  2014-12-19 15:31:48      0   
49974  q7f_lCOKf40idrVSzmoYug     1  2018-03-04 13:19:56      0   
49975  TCoBE_BkDRrK0bWrh5VueQ     2  2017-06-07 23:07:25      4   
49976  r-s-G1yyETRzTALYG9js8A     3  2010-08-23 19:26:49      4   
49977  j9bWpCRwpDVfwVT_V85qeA     0  2014-02-07 03:54:42      0   
49978  -bd4BQcl1ekgo7avaFngIw     0  2018-05-20 01:21:45      0   
49979  W9JHcg3YTWo2-gfLSS4Wlw     0  2017-03-15 04:46:40      0   
49980  faPVqws-x-5k2CQKDNtHxw     1  2017-11-06 20:53:40      0   
49981  M51gw2cz_vXarNBLbKkOxQ     2  2012-07-16 18:47:31      0   
49982  QNiMs-AacTuOJwQAjmkrVA     0  2018-07-08 01:27:31      0   
49983  8WBHKj2davW6hhZWlUQ7DA     0  2017-01-15 03:55:48      0   
49984  xRzr_FDV5S6by9ieeSX8Cw     0  2018-08-14 05:12:20      0   
49985  lKC4TcCzszmd-2Ak2GCH5A     0  2017-04-19 17:50:07      0   
49986  ujHiaprwCQ5ewziu0Vi9rw     2  2016-08-04 07:25:52      2   
49987  KiE81YHZCEdPPlmrXghgzA     0  2018-02-11 11:45:10      0   
49988  vrKcFQPxj1Zzyj93yl-t6g     0  2017-01-02 15:22:53      0   
49989  mPk43gs2O2n06MNR-uDKfg     0  2015-04-01 21:21:51      0   
49990  FGWc5hjTaOql-Rut_bEbVw     4  2017-12-16 15:58:13      3   
49991  F73T-N5lRNL2Gcpg0Q4KKw     0  2017-03-04 04:16:30      0   
49992  5ZzmZjt5-5fsX03BL70DgA     0  2015-07-04 05:19:50      0   
49993  AfEOC5LlBeMt708QEQUihw     2  2013-06-24 23:00:55      3   
49994  nrahyQyopCtajDqUtVVVfA     0  2018-08-05 02:03:58      0   
49995  RJdSwvgAd2TRdQw4iOsrag     0  2015-10-08 03:24:48      0   
49996  coGEHGuUtnABP7KHgGlmRg     0  2018-08-05 02:47:25      0   
49997  OHwVDLnpNApygH-tdR8UNg     1  2013-05-08 01:58:00      0  

In [0]:
x = df['text']
y = df['Predicted_review']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 101)

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv_transformer = CountVectorizer(analyzer = 'word')

In [0]:
x = cv_transformer.fit_transform(x)



In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 101)

In [0]:
from sklearn.naive_bayes import MultinomialNB

In [37]:
nb = MultinomialNB()
nb.fit(x_train, y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [38]:
predictions = nb.predict(x_test)
predictions

array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Neutral',
       'Neutral'], dtype='<U8')

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [40]:
print(confusion_matrix(y_test, predictions))
print("\n")
print(classification_report(y_test, predictions))

[[    4   199   177]
 [    0  1081  1293]
 [   45  1444 10757]]


              precision    recall  f1-score   support

    Negative       0.08      0.01      0.02       380
     Neutral       0.40      0.46      0.42      2374
    Positive       0.88      0.88      0.88     12246

   micro avg       0.79      0.79      0.79     15000
   macro avg       0.45      0.45      0.44     15000
weighted avg       0.78      0.79      0.79     15000



In [42]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rmfr = RandomForestClassifier()
rmfr.fit(x_train,y_train)
predrmfr = rmfr.predict(x_test)
predrmfr

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Positive'], dtype=object)

In [43]:
print(confusion_matrix(y_test, predrmfr))
print("\n")
print(classification_report(y_test, predrmfr))

[[   20    19   341]
 [    1   336  2037]
 [    3   220 12023]]


              precision    recall  f1-score   support

    Negative       0.83      0.05      0.10       380
     Neutral       0.58      0.14      0.23      2374
    Positive       0.83      0.98      0.90     12246

   micro avg       0.83      0.83      0.83     15000
   macro avg       0.75      0.39      0.41     15000
weighted avg       0.80      0.83      0.78     15000



In [0]:
# Support Vector Machine
from sklearn.svm import SVC
svm = SVC(random_state=101)
svm.fit(x_train,y_train)
predsvm = svm.predict(x_test)
predsvm

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [176]:
print(confusion_matrix(y_test, predsvm))
print("\n")
print(classification_report(y_test, predsvm))

[[   0    0   83]
 [   0    0  375]
 [   0    0 2542]]


              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        83
     Neutral       0.00      0.00      0.00       375
    Positive       0.85      1.00      0.92      2542

   micro avg       0.85      0.85      0.85      3000
   macro avg       0.28      0.33      0.31      3000
weighted avg       0.72      0.85      0.78      3000



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [20]:
# K Nearest Neighbour Algorithm
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train,y_train)
predknn = knn.predict(x_test)
predknn

array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Positive'], dtype=object)

In [178]:
print(confusion_matrix(y_test, predknn))
print("\n")
print(classification_report(y_test, predknn))

[[   0    0   83]
 [   0    5  370]
 [   0   11 2531]]


              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        83
     Neutral       0.31      0.01      0.03       375
    Positive       0.85      1.00      0.92      2542

   micro avg       0.85      0.85      0.85      3000
   macro avg       0.39      0.34      0.31      3000
weighted avg       0.76      0.85      0.78      3000



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Prediction and Analysis Using Naive Bayes Classifier

In [21]:

# Negative Review Classified Correct when data Set 50000
pr = df['text'][0]
print(pr)
print("Actual Rating: ",df['stars'][0])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])


total bill for this horrible service? over $8gs. these crooks actually had the nerve to charge us $69 for 3 pills. i checked online the pills can be had for 19 cents each! avoid hospital ers at all costs.
Actual Rating:  1.0
Predicted Rating: Negative


In [25]:
# Positive Misclassified REVIEW when Data set 50000
pr = df['text'][49000]
print(pr)
print("Actual Rating: ",df['stars'][49000])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:",nb.predict(pr_t)[0])


so this pizza place is now called "boca park pizza". and it's not just the name that changed the pizza sucks now ... it's just bad very doughy and oiley... before you could order well done and crispy and get it now good luck - not going here again
Actual Rating:  1.0
Predicted Rating: Positive


In [26]:
# Positive correct classified Review when data set 50000
pr = df['text'][48000]
print(pr)
print("Actual Rating: ",df['stars'][48000])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])


my co-workers always talk about this place so i figured to give it a try with a group of friends. i ordered the 1/2 meat lovers skillet with blueberry protein pancakes....it was bomb! the sweetness of cinnamon and blueberries just went so together with the syrup. the skillet itself was phenomenal. my girlfriend loved her eggs benedict. i think i just found my sunday breakfast joint!
Actual Rating:  4.0
Predicted Rating: Positive


In [27]:
# Misclassified Neutral when data set 50000
pr = df['text'][49764]
print(pr)
print("Actual Rating: ",df['stars'][49764])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])

thailicious - cute name very catchy and the place inside is just as stylish as the name. they have a 2 big screen tvs on both sides of the place and a nice little bar area smack dap in the center back of the room. it's close to my job so i thought today was the day i go check them out during my lunch hour.

service is friendly and fast, i was arrived a little after 11:30, it was still slow, i'm sure the lunch rush was coming soon. but i was able to pick any place to sit.  

after checking out the menu i went with the heaven ginger with chicken, it was ginger, onions, mushrooms, bell peppers & scallions in a house bean sauce and a side of steamed rice & crispy roll.  i also ordered it thai hot.  the heat was a little lacking for me, it was more like a level 2 not a thai hot, the flavor of the dish was good too, it just seemed to be lacking something, it was an ok dish, it wasn't spectacular or mind blowing, just a good lunch.

the salad was a typical iceberg lettuce blend with carrots a

In [41]:
# Classified Correct for Neutral when data set 50000
pr = df['text'][49974]
print(pr)
print("Actual Rating: ",df['stars'][49974])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])

pretty good but making this myself would be hotter and more of a fresh taste.  glad i got the mini.  still good though.  not a lot of healthier drink choices.  had to walk over to jamba juice for a smoothie as the drink.
Actual Rating:  3.0
Predicted Rating: Positive


Prediction and Analysis using Random Forest

Random Forest is been most accurate out of Naive Bayes, SVM and Knn 

In [45]:
# Classified Correct for Neutral when data set 50000 - using Ramdon Forest
pr = df['text'][6]
print(pr)
print("Actual Rating: ",df['stars'][6])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", rmfr.predict(pr_t)[0])

tracy dessert had a big name in hong kong and the one in first markham place has been here for many years now! 

came in for some chinese dessert, and i must say their selection has increased tremendously over the years. i might as well add that the price has also increased tremendously as well. the waitress gave us tea, which i could taste had red date in it. fancy!

a simple taro with coconut with tapioca pearls was like $5.25 or something. basically all the desserts were more than $5. that's crazy! i can literally just make this dessert at home and for a bowl, it would probably cost like $0.50. a few years ago, i think i can still get it for like $3-$4, which is more reasonable, but wow, more than $5 is a little over the top for this dessert. though i must say, it is tracy dessert, and they are a little more on the expensive side. 

i also saw other items on the menu like fish balls, chicken wings, shaved ice. my friend got a mango drink with fresh mango in it! 

i'm also surprised 

In [46]:
# Classified Correct for Positive when data set 50000 - using Ramdon Forest
pr = df['text'][49999]
pr = df['text'][49999]
print(pr)
print("Actual Rating: ",df['stars'][49999])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", rmfr.predict(pr_t)[0])

best place to be for sports events. service and the location is amazing. great staff and the choice of food are huge. delicious foods and great drinks. back and front terrace with tv screens everywhere. the decor is beautiful. good for groups and co-workers.
Actual Rating:  5.0
Predicted Rating: Positive


In [48]:
# Misclassified Instance for Negative review, when data set 50000 - using Ramdon Forest
pr = df['text'][47646]
pr = df['text'][47646]
print(pr)
print("Actual Rating: ",df['stars'][47646])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", rmfr.predict(pr_t)[0])

unfortunately i've seen this smith's go way downhill over the past decade. it used to be clean and have a great variety of organic/natural/vegetarian food. now it's dingy and the natural foods section is half the size it used to be.

i give it three stars because there are occasionally good manager deals there that aren't at other smith's location. i got a bunch of bags of vegan cheese last week for a third of what they usually cost.

update: always long lines (especially at customer service) and stuff out of stock. updating my review to one star to reflect that.
Actual Rating:  1.0
Predicted Rating: Positive


In [49]:
# Correctly Classified Instance for Positve review, when data set 50000 - using Ramdon Forest
pr = df['text'][47000]
pr = df['text'][47000]
print(pr)
print("Actual Rating: ",df['stars'][47000])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", rmfr.predict(pr_t)[0])

always my go to place for the many supplies i always need... i do several crafty things: acrylic paints on canvas, watercolors, drawings, woodworking, sewing, food crafting, making wreaths/holiday decor, jewelry, its endless.

i just wish i would get coupons like "20% off your entire purchase" instead of "40% off one item." i never buy any one thing over $10, and you can't use it on things already on sale. whatever, i can't stop shopping there;there are too few stores like this as it is. also walmarts art section isn't as good as this one store. lol
Actual Rating:  4.0
Predicted Rating: Positive
