In [0]:
import numpy as np
#import nltk
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import f1_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
import seaborn as sns
import string

In [51]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import pandas as pd
import json
import csv
yelp = []
for line in open('/content/gdrive/My Drive/255-yelp-assignment1/review_top300000.json', 'r'):
    yelp.append(json.loads(line))


In [53]:
df = pd.DataFrame(yelp)
df

business_id  cool                 date  funny  \
0       ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1       NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2       WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3       ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4       b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   
5       eU_713ec6fTGNO4BegRaww     0  2013-01-20 13:25:59      0   
6       3fw2X5bZYeW9xCz_zGhOHg     5  2016-05-07 01:21:02      4   
7       zvO-PJCpNk4fgAVUnExYAA     1  2010-10-05 19:12:35      1   
8       b2jN2mm9Wf3RcrZCgfo1cg     0  2015-01-18 14:04:18      0   
9       oxwGyA17NL6c5t1Etg5WgQ     1  2012-02-29 21:52:43      0   
10      8mIrX_LrOnAqWsB5JrOojQ     0  2011-11-30 02:11:15      0   
11      mRUVMJkUGxrByzMQ2MuOpA     0  2017-12-15 23:27:08      1   
12      FxLfqxdYPA6Z85PFKaqLrg     0  2016-05-07 01:36:53      0   
13      LUN6swQYa4xJKaM_UEUOEw     0  2018-04-27 20:25:26      0   
14      AakkkTuGZA2KBodKi2_u8A     0  2012-07-16 00:37:14      1   
15      YvrylyuWgbP90RgMqZQVnQ     0  2017-04-07 21:27:49      0   
16      NyLYY8q1-H3hfsTwuwLPCg     0  2015-01-03 22:47:34      0   
17      cHdJXLlKNWixBXpDwEGb_A     1  2015-04-01 16:30:00      7   
18      6lj2BJ4tJeu7db5asGHQ4w     0  2017-05-26 01:23:19      0   
19      y-Iw6dZflNix4BdwIyTNGA     0  2014-06-27 21:19:23      0   
20      qx6WhZ42eDKmBchZDax4dQ     0  2017-03-27 01:14:37      0   
21      Mem13A3C202RzT53npn4NA     9  2017-05-13 10:41:43      6   
22      I4Nr-MVc26qWr08-S3Q1ow     0  2016-01-17 05:26:22      0   
23      d_L-rfS1vT3JMzgCUGtiow     0  2016-07-25 03:57:19      0   
24      Sfc8Haz2Yri8Mo1L0E0TsA     0  2012-11-06 03:41:43      0   
25      FQ1wBQb3aNeRMThSQEV0Qg     0  2013-12-07 02:32:45      0   
26      hd5xm20tfSa70-6UqD9-bg     1  2014-08-10 22:07:35      1   
27      Gyrez6K8f1AyR7dzW9fvAw     1  2013-12-28 22:28:08      0   
28      9nTF596jDvBBia2EXXiOOg     0  2014-04-19 15:03:17      0   
29      SNL64axQhCO6Z7ohcWg3wA     0  2017-02-09 03:43:25      0   
...                        ...   ...                  ...    ...   
299970  8TBt9XAVZIZR2Y0EqBHskg     0  2017-10-07 20:33:23      0   
299971  UYnkAU9BNjQmcFXtFgGWvg     1  2014-08-17 01:16:43      0   
299972  lywduRzRWrZLD03L2ZINhQ     0  2015-11-13 03:20:30      0   
299973  LL7EY-YARSY41n98P9509w     1  2014-05-15 18:20:20      1   
299974  IETo39FTLKPa5-7QYBC4lw     0  2017-02-01 22:20:50      0   
299975  aVkVDJ01OgvNwhlCUz_bng     0  2010-10-16 23:52:38      0   
299976  osSwv6CJy5hDKQdOKeyTow     0  2016-05-24 16:08:16      0   
299977  SVGApDPNdpFlEjwRQThCxA     0  2015-06-13 03:58:51      0   
299978  PWW_jT4tHP_r1S18ePJyTQ     1  2014-07-19 03:04:39      0   
299979  l-D0uS-tgmhkFpHKBXvPQA     0  2018-06-29 16:33:04      0   
299980  LFfYe-hh1NKFtUKV3LUgfg     1  2010-10-21 02:22:03      0   
299981  I4Nr-MVc26qWr08-S3Q1ow     0  2018-07-21 22:30:20      0   
299982  UeEzvTGkSyaHRvWTlZ1ISA     1  2017-10-29 19:37:25      0   
299983  uuGL8diLlHfeUeFuod3F-w     0  2016-11-30 23:48:58      1   
299984  NjDC1Evc2Wa6ykj8xVpoUw     0  2013-11-23 02:41:54      0   
299985  Hky64JGIDwUOv_PaI1BjHA     2  2017-12-08 15:22:09      0   
299986  uuGL8diLlHfeUeFuod3F-w     2  2017-09-27 06:29:14      0   
299987  NZAxQxXH0YkSzPOKd_Nv-w     0  2014-06-01 23:53:12      0   
299988  FnzYaH-uFANFyjrVuJkpwg     0  2015-08-03 20:34:01      0   
299989  seJ7Hlwr583gNGkT3amzIA     0  2010-02-07 02:57:16      0   
299990  d_L-rfS1vT3JMzgCUGtiow     0  2007-02-14 04:07:51      0   
299991  C6eijBK1l2FOV_8MGnmsCA     1  2018-03-22 20:07:11      0   
299992  ue39-OmCyusuxzY_9q4vGg     0  2017-05-25 15:45:05      0   
299993  5nMvlKW5n2-O0tT44DYnDQ     0  2013-11-02 02:18:51      0   
299994  gSdNk7XZ0ytt9ojwuVwJdA     0  2015-07-21 17:08:05      0   
299995  thr3T1m-xd2RJoiH6hwAYg     1  2014-07-03 04:10:40      1   
299996  0PMMhCAz2S5dmcA9mJ3dRg     0  2017-01-22 02:32:46      2   
299997 

In [54]:
## convert text to lower case
df.text = df.text.str.lower()

## remove unnecessary punctuation
df['removed_punct_text']= df.text.str.replace('\n',''). \
                                          str.replace('[!"#$%&\()*+,-./:;<=>?@[\\]^_`{|}~]','')
df.head()

business_id  cool                 date  funny  \
0  ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1  NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2  WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3  ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4  b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   

                review_id  stars  \
0  Q1sbwvVQXV2734tPgoKj4Q    1.0   
1  GJXCdrto3ASJOqKeVWPi6Q    5.0   
2  2TzJjDVDEuAW6MR5Vuc1ug    5.0   
3  yi0R0Ugj_xUx_Nek0-_Qig    5.0   
4  11a8sVPMUFtaC7_ABRkmtw    1.0   

                                                text  useful  \
0  total bill for this horrible service? over $8g...       6   
1  i *adore* travis at the hard rock's new kelly ...       0   
2  i have to say that this office really has it t...       3   
3  went in for a lunch. steak sandwich was delici...       0   
4  today was my second out of three sessions i ha...       7   

                  user_id                                 removed_punct_text  
0  hG7b0MtEbXx5QzbzE6C_VA  total bill for this horrible service over 8gs ...  
1  yXQM5uF2jS6es16SJzNHfg  i adore travis at the hard rock's new kelly ca...  
2  n6-Gk65cPZL6Uz8qRm3NYw  i have to say that this office really has it t...  
3  dacAIZ6fTM6mqwW5uxkskg  went in for a lunch steak sandwich was delicio...  
4  ssoyf2_x0EQMed6fgHeMyQ  today was my second out of three sessions i ha...

In [55]:
positive_words=["good","great","love","best","fantastic","healthiest","definitely","authentic","professional","knowledgeable","confident","polite","friendly","free","wifi","pretty","priceless","privilege","prompt","awesome"]
negative_words=["horrible","slow","irritation","disappointed","awful","abruptly","ashamed","awful"]
neutral_words=["fine","average","ok","satisfy","overall","unfortunately","much","wont","just","worth","still", "though"]
mergedlist = positive_words + negative_words+neutral_words
print(mergedlist)

['good', 'great', 'love', 'best', 'fantastic', 'healthiest', 'definitely', 'authentic', 'professional', 'knowledgeable', 'confident', 'polite', 'friendly', 'free', 'wifi', 'pretty', 'priceless', 'privilege', 'prompt', 'awesome', 'horrible', 'slow', 'irritation', 'disappointed', 'awful', 'abruptly', 'ashamed', 'awful', 'fine', 'average', 'ok', 'satisfy', 'overall', 'unfortunately', 'much', 'wont', 'just', 'worth', 'still', 'though']


In [56]:
#reviews = "good yes"
import nltk
nltk.download('punkt')
Cust = []
from nltk.tokenize import sent_tokenize, word_tokenize
for r in df['text']: # counter for month indices
    review = word_tokenize(r)
    pos = 0
    neg = 0
    neu = 0
    for word in review:
        if word in mergedlist:
            if word in positive_words:
             pos = pos+1
            elif word in negative_words:
             neg = neg+1
            elif word in neutral_words:
             neu = neu +1
    #monthly_mean.append(s/n)
    if pos >= neg and pos >= neu:
     Cust.append('Positive')
    elif neg >= neu:
     Cust.append('Negative')
    else:
     Cust.append('Neutral') 
#print(pos)
#print(neg)
df['Predicted_review'] = Cust 
df

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


business_id  cool                 date  funny  \
0       ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1       NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2       WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3       ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4       b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   
5       eU_713ec6fTGNO4BegRaww     0  2013-01-20 13:25:59      0   
6       3fw2X5bZYeW9xCz_zGhOHg     5  2016-05-07 01:21:02      4   
7       zvO-PJCpNk4fgAVUnExYAA     1  2010-10-05 19:12:35      1   
8       b2jN2mm9Wf3RcrZCgfo1cg     0  2015-01-18 14:04:18      0   
9       oxwGyA17NL6c5t1Etg5WgQ     1  2012-02-29 21:52:43      0   
10      8mIrX_LrOnAqWsB5JrOojQ     0  2011-11-30 02:11:15      0   
11      mRUVMJkUGxrByzMQ2MuOpA     0  2017-12-15 23:27:08      1   
12      FxLfqxdYPA6Z85PFKaqLrg     0  2016-05-07 01:36:53      0   
13      LUN6swQYa4xJKaM_UEUOEw     0  2018-04-27 20:25:26      0   
14      AakkkTuGZA2KBodKi2_u8A     0  2012-07-16 00:37:14      1   
15      YvrylyuWgbP90RgMqZQVnQ     0  2017-04-07 21:27:49      0   
16      NyLYY8q1-H3hfsTwuwLPCg     0  2015-01-03 22:47:34      0   
17      cHdJXLlKNWixBXpDwEGb_A     1  2015-04-01 16:30:00      7   
18      6lj2BJ4tJeu7db5asGHQ4w     0  2017-05-26 01:23:19      0   
19      y-Iw6dZflNix4BdwIyTNGA     0  2014-06-27 21:19:23      0   
20      qx6WhZ42eDKmBchZDax4dQ     0  2017-03-27 01:14:37      0   
21      Mem13A3C202RzT53npn4NA     9  2017-05-13 10:41:43      6   
22      I4Nr-MVc26qWr08-S3Q1ow     0  2016-01-17 05:26:22      0   
23      d_L-rfS1vT3JMzgCUGtiow     0  2016-07-25 03:57:19      0   
24      Sfc8Haz2Yri8Mo1L0E0TsA     0  2012-11-06 03:41:43      0   
25      FQ1wBQb3aNeRMThSQEV0Qg     0  2013-12-07 02:32:45      0   
26      hd5xm20tfSa70-6UqD9-bg     1  2014-08-10 22:07:35      1   
27      Gyrez6K8f1AyR7dzW9fvAw     1  2013-12-28 22:28:08      0   
28      9nTF596jDvBBia2EXXiOOg     0  2014-04-19 15:03:17      0   
29      SNL64axQhCO6Z7ohcWg3wA     0  2017-02-09 03:43:25      0   
...                        ...   ...                  ...    ...   
299970  8TBt9XAVZIZR2Y0EqBHskg     0  2017-10-07 20:33:23      0   
299971  UYnkAU9BNjQmcFXtFgGWvg     1  2014-08-17 01:16:43      0   
299972  lywduRzRWrZLD03L2ZINhQ     0  2015-11-13 03:20:30      0   
299973  LL7EY-YARSY41n98P9509w     1  2014-05-15 18:20:20      1   
299974  IETo39FTLKPa5-7QYBC4lw     0  2017-02-01 22:20:50      0   
299975  aVkVDJ01OgvNwhlCUz_bng     0  2010-10-16 23:52:38      0   
299976  osSwv6CJy5hDKQdOKeyTow     0  2016-05-24 16:08:16      0   
299977  SVGApDPNdpFlEjwRQThCxA     0  2015-06-13 03:58:51      0   
299978  PWW_jT4tHP_r1S18ePJyTQ     1  2014-07-19 03:04:39      0   
299979  l-D0uS-tgmhkFpHKBXvPQA     0  2018-06-29 16:33:04      0   
299980  LFfYe-hh1NKFtUKV3LUgfg     1  2010-10-21 02:22:03      0   
299981  I4Nr-MVc26qWr08-S3Q1ow     0  2018-07-21 22:30:20      0   
299982  UeEzvTGkSyaHRvWTlZ1ISA     1  2017-10-29 19:37:25      0   
299983  uuGL8diLlHfeUeFuod3F-w     0  2016-11-30 23:48:58      1   
299984  NjDC1Evc2Wa6ykj8xVpoUw     0  2013-11-23 02:41:54      0   
299985  Hky64JGIDwUOv_PaI1BjHA     2  2017-12-08 15:22:09      0   
299986  uuGL8diLlHfeUeFuod3F-w     2  2017-09-27 06:29:14      0   
299987  NZAxQxXH0YkSzPOKd_Nv-w     0  2014-06-01 23:53:12      0   
299988  FnzYaH-uFANFyjrVuJkpwg     0  2015-08-03 20:34:01      0   
299989  seJ7Hlwr583gNGkT3amzIA     0  2010-02-07 02:57:16      0   
299990  d_L-rfS1vT3JMzgCUGtiow     0  2007-02-14 04:07:51      0   
299991  C6eijBK1l2FOV_8MGnmsCA     1  2018-03-22 20:07:11      0   
299992  ue39-OmCyusuxzY_9q4vGg     0  2017-05-25 15:45:05      0   
299993  5nMvlKW5n2-O0tT44DYnDQ     0  2013-11-02 02:18:51      0   
299994  gSdNk7XZ0ytt9ojwuVwJdA     0  2015-07-21 17:08:05      0   
299995  thr3T1m-xd2RJoiH6hwAYg     1  2014-07-03 04:10:40      1   
299996  0PMMhCAz2S5dmcA9mJ3dRg     0  2017-01-22 02:32:46      2   
299997 

In [0]:
x = df['text']
y = df['Predicted_review']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 101)

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv_transformer = CountVectorizer(analyzer = 'word')

In [0]:
x = cv_transformer.fit_transform(x)



In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 101)

In [0]:
from sklearn.naive_bayes import MultinomialNB

In [62]:
nb = MultinomialNB()
nb.fit(x_train, y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [63]:
predictions = nb.predict(x_test)
predictions

array(['Positive', 'Positive', 'Positive', ..., 'Neutral', 'Positive',
       'Positive'], dtype='<U8')

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [65]:
print(confusion_matrix(y_test, predictions))
print("\n")
print(classification_report(y_test, predictions))

[[  164  1169   892]
 [    7  8014  6880]
 [  238 10074 62562]]


              precision    recall  f1-score   support

    Negative       0.40      0.07      0.12      2225
     Neutral       0.42      0.54      0.47     14901
    Positive       0.89      0.86      0.87     72874

   micro avg       0.79      0.79      0.79     90000
   macro avg       0.57      0.49      0.49     90000
weighted avg       0.80      0.79      0.79     90000



In [66]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rmfr = RandomForestClassifier()
rmfr.fit(x_train,y_train)
predrmfr = rmfr.predict(x_test)
predrmfr

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Positive'], dtype=object)

In [67]:
print(confusion_matrix(y_test, predrmfr))
print("\n")
print(classification_report(y_test, predrmfr))

[[  122   139  1964]
 [   10  2468 12423]
 [   19  1572 71283]]


              precision    recall  f1-score   support

    Negative       0.81      0.05      0.10      2225
     Neutral       0.59      0.17      0.26     14901
    Positive       0.83      0.98      0.90     72874

   micro avg       0.82      0.82      0.82     90000
   macro avg       0.74      0.40      0.42     90000
weighted avg       0.79      0.82      0.77     90000



Prediction and Analysis Using Naive Bayes Classifier

In [69]:

# Negative Review Classified Correct when data Set 300000
pr = df['text'][0]
print(pr)
print("Actual Rating: ",df['stars'][0])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])


total bill for this horrible service? over $8gs. these crooks actually had the nerve to charge us $69 for 3 pills. i checked online the pills can be had for 19 cents each! avoid hospital ers at all costs.
Actual Rating:  1.0
Predicted Rating: Negative


In [70]:
# Positive Misclassified REVIEW when Data set 300000
pr = df['text'][49000]
print(pr)
print("Actual Rating: ",df['stars'][49000])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:",nb.predict(pr_t)[0])


so this pizza place is now called "boca park pizza". and it's not just the name that changed the pizza sucks now ... it's just bad very doughy and oiley... before you could order well done and crispy and get it now good luck - not going here again
Actual Rating:  1.0
Predicted Rating: Neutral


In [71]:
# Positive correct classified Review when data set 300000
pr = df['text'][48000]
print(pr)
print("Actual Rating: ",df['stars'][48000])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])


my co-workers always talk about this place so i figured to give it a try with a group of friends. i ordered the 1/2 meat lovers skillet with blueberry protein pancakes....it was bomb! the sweetness of cinnamon and blueberries just went so together with the syrup. the skillet itself was phenomenal. my girlfriend loved her eggs benedict. i think i just found my sunday breakfast joint!
Actual Rating:  4.0
Predicted Rating: Positive


In [72]:
# Misclassified Neutral when data set 300000
pr = df['text'][49764]
print(pr)
print("Actual Rating: ",df['stars'][49764])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])

thailicious - cute name very catchy and the place inside is just as stylish as the name. they have a 2 big screen tvs on both sides of the place and a nice little bar area smack dap in the center back of the room. it's close to my job so i thought today was the day i go check them out during my lunch hour.

service is friendly and fast, i was arrived a little after 11:30, it was still slow, i'm sure the lunch rush was coming soon. but i was able to pick any place to sit.  

after checking out the menu i went with the heaven ginger with chicken, it was ginger, onions, mushrooms, bell peppers & scallions in a house bean sauce and a side of steamed rice & crispy roll.  i also ordered it thai hot.  the heat was a little lacking for me, it was more like a level 2 not a thai hot, the flavor of the dish was good too, it just seemed to be lacking something, it was an ok dish, it wasn't spectacular or mind blowing, just a good lunch.

the salad was a typical iceberg lettuce blend with carrots a

In [73]:
# Classified Correct for Neutral when data set 300000
pr = df['text'][49974]
print(pr)
print("Actual Rating: ",df['stars'][49974])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])

pretty good but making this myself would be hotter and more of a fresh taste.  glad i got the mini.  still good though.  not a lot of healthier drink choices.  had to walk over to jamba juice for a smoothie as the drink.
Actual Rating:  3.0
Predicted Rating: Positive


Prediction and Analysis using Random Forest

Random Forest is been most accurate out of Naive Bayes, SVM and Knn 

In [74]:
# Classified Correct for Neutral when data set 300000 - using Ramdon Forest
pr = df['text'][6]
print(pr)
print("Actual Rating: ",df['stars'][6])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", rmfr.predict(pr_t)[0])

tracy dessert had a big name in hong kong and the one in first markham place has been here for many years now! 

came in for some chinese dessert, and i must say their selection has increased tremendously over the years. i might as well add that the price has also increased tremendously as well. the waitress gave us tea, which i could taste had red date in it. fancy!

a simple taro with coconut with tapioca pearls was like $5.25 or something. basically all the desserts were more than $5. that's crazy! i can literally just make this dessert at home and for a bowl, it would probably cost like $0.50. a few years ago, i think i can still get it for like $3-$4, which is more reasonable, but wow, more than $5 is a little over the top for this dessert. though i must say, it is tracy dessert, and they are a little more on the expensive side. 

i also saw other items on the menu like fish balls, chicken wings, shaved ice. my friend got a mango drink with fresh mango in it! 

i'm also surprised 

In [77]:
# Classified Correct for Positive when data set 300000 - using Ramdon Forest
pr = df['text'][299989]
pr = df['text'][299989]
print(pr)
print("Actual Rating: ",df['stars'][299989])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", rmfr.predict(pr_t)[0])

this place seems virtually unknown, but i'd say it's a hidden gem.  

my only complaint is it's very tacky inside, but i can overlook that part.  the staff is super friendly and attentive--almost too attentive.  (i felt like i was a martian for so often not needing anything else when they asked.)

i've been a couple of times.  the standouts are a very tender pork with green chile; chicken mole negro, and a chile relleno with mexican white cheese and a spicy cream sauce.
Actual Rating:  4.0
Predicted Rating: Positive


In [96]:
# Misclassified Instance for Negative review, when data set 50000 - using Ramdon Forest
pr = df['text'][6]
pr = df['text'][6]
print(pr)
print("Actual Rating: ",df['stars'][6])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", rmfr.predict(pr_t)[0])

tracy dessert had a big name in hong kong and the one in first markham place has been here for many years now! 

came in for some chinese dessert, and i must say their selection has increased tremendously over the years. i might as well add that the price has also increased tremendously as well. the waitress gave us tea, which i could taste had red date in it. fancy!

a simple taro with coconut with tapioca pearls was like $5.25 or something. basically all the desserts were more than $5. that's crazy! i can literally just make this dessert at home and for a bowl, it would probably cost like $0.50. a few years ago, i think i can still get it for like $3-$4, which is more reasonable, but wow, more than $5 is a little over the top for this dessert. though i must say, it is tracy dessert, and they are a little more on the expensive side. 

i also saw other items on the menu like fish balls, chicken wings, shaved ice. my friend got a mango drink with fresh mango in it! 

i'm also surprised 

In [49]:
# Correctly Classified Instance for Positve review, when data set 50000 - using Ramdon Forest
pr = df['text'][47000]
pr = df['text'][47000]
print(pr)
print("Actual Rating: ",df['stars'][47000])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", rmfr.predict(pr_t)[0])

always my go to place for the many supplies i always need... i do several crafty things: acrylic paints on canvas, watercolors, drawings, woodworking, sewing, food crafting, making wreaths/holiday decor, jewelry, its endless.

i just wish i would get coupons like "20% off your entire purchase" instead of "40% off one item." i never buy any one thing over $10, and you can't use it on things already on sale. whatever, i can't stop shopping there;there are too few stores like this as it is. also walmarts art section isn't as good as this one store. lol
Actual Rating:  4.0
Predicted Rating: Positive
