In [0]:
import numpy as np
#import nltk
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import f1_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
import seaborn as sns
import string

In [158]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import pandas as pd
import json
import csv
yelp = []
for line in open('/content/gdrive/My Drive/255-yelp-assignment1/review_top10000.json', 'r'):
    yelp.append(json.loads(line))


In [160]:
df = pd.DataFrame(yelp)
df

business_id  cool                 date  funny  \
0     ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1     NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2     WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3     ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4     b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   
5     eU_713ec6fTGNO4BegRaww     0  2013-01-20 13:25:59      0   
6     3fw2X5bZYeW9xCz_zGhOHg     5  2016-05-07 01:21:02      4   
7     zvO-PJCpNk4fgAVUnExYAA     1  2010-10-05 19:12:35      1   
8     b2jN2mm9Wf3RcrZCgfo1cg     0  2015-01-18 14:04:18      0   
9     oxwGyA17NL6c5t1Etg5WgQ     1  2012-02-29 21:52:43      0   
10    8mIrX_LrOnAqWsB5JrOojQ     0  2011-11-30 02:11:15      0   
11    mRUVMJkUGxrByzMQ2MuOpA     0  2017-12-15 23:27:08      1   
12    FxLfqxdYPA6Z85PFKaqLrg     0  2016-05-07 01:36:53      0   
13    LUN6swQYa4xJKaM_UEUOEw     0  2018-04-27 20:25:26      0   
14    AakkkTuGZA2KBodKi2_u8A     0  2012-07-16 00:37:14      1   
15    YvrylyuWgbP90RgMqZQVnQ     0  2017-04-07 21:27:49      0   
16    NyLYY8q1-H3hfsTwuwLPCg     0  2015-01-03 22:47:34      0   
17    cHdJXLlKNWixBXpDwEGb_A     1  2015-04-01 16:30:00      7   
18    6lj2BJ4tJeu7db5asGHQ4w     0  2017-05-26 01:23:19      0   
19    y-Iw6dZflNix4BdwIyTNGA     0  2014-06-27 21:19:23      0   
20    qx6WhZ42eDKmBchZDax4dQ     0  2017-03-27 01:14:37      0   
21    Mem13A3C202RzT53npn4NA     9  2017-05-13 10:41:43      6   
22    I4Nr-MVc26qWr08-S3Q1ow     0  2016-01-17 05:26:22      0   
23    d_L-rfS1vT3JMzgCUGtiow     0  2016-07-25 03:57:19      0   
24    Sfc8Haz2Yri8Mo1L0E0TsA     0  2012-11-06 03:41:43      0   
25    FQ1wBQb3aNeRMThSQEV0Qg     0  2013-12-07 02:32:45      0   
26    hd5xm20tfSa70-6UqD9-bg     1  2014-08-10 22:07:35      1   
27    Gyrez6K8f1AyR7dzW9fvAw     1  2013-12-28 22:28:08      0   
28    9nTF596jDvBBia2EXXiOOg     0  2014-04-19 15:03:17      0   
29    SNL64axQhCO6Z7ohcWg3wA     0  2017-02-09 03:43:25      0   
...                      ...   ...                  ...    ...   
9970  XhUec_6-kgPy1_ZYUrzvPQ     0  2014-11-12 18:09:15      0   
9971  5FIOXmUE3qMviX9GafGH-Q     0  2017-03-15 13:09:07      1   
9972  QqJFnv7q3b2VSSvqlUr4Cg     0  2015-11-18 19:48:04      0   
9973  mfVrZNl4HHc8sxTl8rjztg     1  2015-07-28 16:35:25      2   
9974  4ritTGFnNxmKnKm-UX3kPQ     0  2016-08-13 00:10:44      0   
9975  77h11eWv6HKJAgojLx8G4w     0  2018-04-04 14:30:20      0   
9976  FRfB3ZCY2szqp9ETT0tfjg     0  2013-12-07 10:40:47      1   
9977  SVhM3Pxjw-PUPr1sBghqlw     0  2017-06-06 21:01:18      0   
9978  6s7uduX1Q1KSjOKvwxYkRA     0  2013-05-07 12:49:30      0   
9979  gaSP19bI-CJZ-yRA4lvoUw     0  2008-12-04 19:51:32      0   
9980  KxmzyLoX_u9Dx2ZoMwSYzg     0  2016-01-17 18:09:33      0   
9981  CpyDEbemEm8F4vaUYcL_VQ     0  2017-08-28 20:09:17      0   
9982  cHdJXLlKNWixBXpDwEGb_A     1  2013-07-13 01:07:56      2   
9983  yYkvonvBGZB6UMnpzr6Ryw     0  2017-04-19 08:08:49      0   
9984  tjAeaGdxf7I4xN9M7wGJNQ     0  2015-08-07 02:19:55      0   
9985  46hnat0aLao-qYWZkN9aBg     0  2016-11-22 00:31:54      0   
9986  jYU4Nd71giCWpLuj5JIxgg     0  2018-01-21 08:59:34      0   
9987  eFcpMAgG5OLzgElmnO2DUQ     0  2018-05-19 01:53:15      0   
9988  EneqsOFGCK4KXofNHsc5aQ     2  2017-12-29 19:19:14      2   
9989  cMoAyO10kXgzNEGSnUUjCA     7  2010-01-08 20:20:52      5   
9990  i0mkpJFYJizVsOSfsivRVg     0  2015-08-19 18:00:03      0   
9991  9pkcj5Lo9laX-bGdiASriA     0  2011-10-27 18:50:37      0   
9992  JYzP9hYTwOQhFeCEAx2zng     0  2017-05-13 19:15:50      0   
9993  vNPJbqYuJEFDPOLhoq3bFA     0  2015-04-28 20:31:58      0   
9994  ZCYCNWA98718SZ0A4bHD7A     0  2018-06-09 00:24:40      0   
9995  vdKUDXI1j89VO65Krg6VGg     0  2018-05-28 22:53:56      0   
9996  TxNeo206T0jMvRRQ4nKSIg     1  2013-01-02 21:09:13      1   
9997  4z_hAnw2UV5CzfcjtVvWsg     0  2017-11-18 21:07:11      0   
9998  ALUqFoEbPIXEwdX7QbyR_Q     0  2015-04-29 00:51:46  

In [161]:
## convert text to lower case
df.text = df.text.str.lower()

## remove unnecessary punctuation
df['removed_punct_text']= df.text.str.replace('\n',''). \
                                          str.replace('[!"#$%&\()*+,-./:;<=>?@[\\]^_`{|}~]','')
df.head()

business_id  cool                 date  funny  \
0  ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1  NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2  WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3  ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4  b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   

                review_id  stars  \
0  Q1sbwvVQXV2734tPgoKj4Q    1.0   
1  GJXCdrto3ASJOqKeVWPi6Q    5.0   
2  2TzJjDVDEuAW6MR5Vuc1ug    5.0   
3  yi0R0Ugj_xUx_Nek0-_Qig    5.0   
4  11a8sVPMUFtaC7_ABRkmtw    1.0   

                                                text  useful  \
0  total bill for this horrible service? over $8g...       6   
1  i *adore* travis at the hard rock's new kelly ...       0   
2  i have to say that this office really has it t...       3   
3  went in for a lunch. steak sandwich was delici...       0   
4  today was my second out of three sessions i ha...       7   

                  user_id                                 removed_punct_text  
0  hG7b0MtEbXx5QzbzE6C_VA  total bill for this horrible service over 8gs ...  
1  yXQM5uF2jS6es16SJzNHfg  i adore travis at the hard rock's new kelly ca...  
2  n6-Gk65cPZL6Uz8qRm3NYw  i have to say that this office really has it t...  
3  dacAIZ6fTM6mqwW5uxkskg  went in for a lunch steak sandwich was delicio...  
4  ssoyf2_x0EQMed6fgHeMyQ  today was my second out of three sessions i ha...

In [162]:
positive_words=["good","great","love","best","fantastic","healthiest","definitely","authentic","professional","knowledgeable","confident","polite","friendly","free","wifi","pretty","priceless","privilege","prompt","awesome"]
negative_words=["horrible","slow","irritation","disappointed","awful","abruptly","ashamed","awful"]
neutral_words=["fine","average","ok","satisfy","overall","unfortunately","much","wont","just","worth"]
mergedlist = positive_words + negative_words+neutral_words
print(mergedlist)

['good', 'great', 'love', 'best', 'fantastic', 'healthiest', 'definitely', 'authentic', 'professional', 'knowledgeable', 'confident', 'polite', 'friendly', 'free', 'wifi', 'pretty', 'priceless', 'privilege', 'prompt', 'awesome', 'horrible', 'slow', 'irritation', 'disappointed', 'awful', 'abruptly', 'ashamed', 'awful', 'fine', 'average', 'ok', 'satisfy', 'overall', 'unfortunately', 'much', 'wont', 'just', 'worth']


In [163]:
#reviews = "good yes"
import nltk
nltk.download('punkt')
Cust = []
from nltk.tokenize import sent_tokenize, word_tokenize
for r in df['text']: # counter for month indices
    review = word_tokenize(r)
    pos = 0
    neg = 0
    neu = 0
    for word in review:
        if word in mergedlist:
            if word in positive_words:
             pos = pos+1
            elif word in negative_words:
             neg = neg+1
            elif word in neutral_words:
             neu = neu +1
    #monthly_mean.append(s/n)
    if pos >= neg and pos >= neu:
     Cust.append('Positive')
    elif neg >= neu:
     Cust.append('Negative')
    else:
     Cust.append('Neutral') 
#print(pos)
#print(neg)
df['Predicted_review'] = Cust 
df

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


business_id  cool                 date  funny  \
0     ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1     NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2     WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3     ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4     b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   
5     eU_713ec6fTGNO4BegRaww     0  2013-01-20 13:25:59      0   
6     3fw2X5bZYeW9xCz_zGhOHg     5  2016-05-07 01:21:02      4   
7     zvO-PJCpNk4fgAVUnExYAA     1  2010-10-05 19:12:35      1   
8     b2jN2mm9Wf3RcrZCgfo1cg     0  2015-01-18 14:04:18      0   
9     oxwGyA17NL6c5t1Etg5WgQ     1  2012-02-29 21:52:43      0   
10    8mIrX_LrOnAqWsB5JrOojQ     0  2011-11-30 02:11:15      0   
11    mRUVMJkUGxrByzMQ2MuOpA     0  2017-12-15 23:27:08      1   
12    FxLfqxdYPA6Z85PFKaqLrg     0  2016-05-07 01:36:53      0   
13    LUN6swQYa4xJKaM_UEUOEw     0  2018-04-27 20:25:26      0   
14    AakkkTuGZA2KBodKi2_u8A     0  2012-07-16 00:37:14      1   
15    YvrylyuWgbP90RgMqZQVnQ     0  2017-04-07 21:27:49      0   
16    NyLYY8q1-H3hfsTwuwLPCg     0  2015-01-03 22:47:34      0   
17    cHdJXLlKNWixBXpDwEGb_A     1  2015-04-01 16:30:00      7   
18    6lj2BJ4tJeu7db5asGHQ4w     0  2017-05-26 01:23:19      0   
19    y-Iw6dZflNix4BdwIyTNGA     0  2014-06-27 21:19:23      0   
20    qx6WhZ42eDKmBchZDax4dQ     0  2017-03-27 01:14:37      0   
21    Mem13A3C202RzT53npn4NA     9  2017-05-13 10:41:43      6   
22    I4Nr-MVc26qWr08-S3Q1ow     0  2016-01-17 05:26:22      0   
23    d_L-rfS1vT3JMzgCUGtiow     0  2016-07-25 03:57:19      0   
24    Sfc8Haz2Yri8Mo1L0E0TsA     0  2012-11-06 03:41:43      0   
25    FQ1wBQb3aNeRMThSQEV0Qg     0  2013-12-07 02:32:45      0   
26    hd5xm20tfSa70-6UqD9-bg     1  2014-08-10 22:07:35      1   
27    Gyrez6K8f1AyR7dzW9fvAw     1  2013-12-28 22:28:08      0   
28    9nTF596jDvBBia2EXXiOOg     0  2014-04-19 15:03:17      0   
29    SNL64axQhCO6Z7ohcWg3wA     0  2017-02-09 03:43:25      0   
...                      ...   ...                  ...    ...   
9970  XhUec_6-kgPy1_ZYUrzvPQ     0  2014-11-12 18:09:15      0   
9971  5FIOXmUE3qMviX9GafGH-Q     0  2017-03-15 13:09:07      1   
9972  QqJFnv7q3b2VSSvqlUr4Cg     0  2015-11-18 19:48:04      0   
9973  mfVrZNl4HHc8sxTl8rjztg     1  2015-07-28 16:35:25      2   
9974  4ritTGFnNxmKnKm-UX3kPQ     0  2016-08-13 00:10:44      0   
9975  77h11eWv6HKJAgojLx8G4w     0  2018-04-04 14:30:20      0   
9976  FRfB3ZCY2szqp9ETT0tfjg     0  2013-12-07 10:40:47      1   
9977  SVhM3Pxjw-PUPr1sBghqlw     0  2017-06-06 21:01:18      0   
9978  6s7uduX1Q1KSjOKvwxYkRA     0  2013-05-07 12:49:30      0   
9979  gaSP19bI-CJZ-yRA4lvoUw     0  2008-12-04 19:51:32      0   
9980  KxmzyLoX_u9Dx2ZoMwSYzg     0  2016-01-17 18:09:33      0   
9981  CpyDEbemEm8F4vaUYcL_VQ     0  2017-08-28 20:09:17      0   
9982  cHdJXLlKNWixBXpDwEGb_A     1  2013-07-13 01:07:56      2   
9983  yYkvonvBGZB6UMnpzr6Ryw     0  2017-04-19 08:08:49      0   
9984  tjAeaGdxf7I4xN9M7wGJNQ     0  2015-08-07 02:19:55      0   
9985  46hnat0aLao-qYWZkN9aBg     0  2016-11-22 00:31:54      0   
9986  jYU4Nd71giCWpLuj5JIxgg     0  2018-01-21 08:59:34      0   
9987  eFcpMAgG5OLzgElmnO2DUQ     0  2018-05-19 01:53:15      0   
9988  EneqsOFGCK4KXofNHsc5aQ     2  2017-12-29 19:19:14      2   
9989  cMoAyO10kXgzNEGSnUUjCA     7  2010-01-08 20:20:52      5   
9990  i0mkpJFYJizVsOSfsivRVg     0  2015-08-19 18:00:03      0   
9991  9pkcj5Lo9laX-bGdiASriA     0  2011-10-27 18:50:37      0   
9992  JYzP9hYTwOQhFeCEAx2zng     0  2017-05-13 19:15:50      0   
9993  vNPJbqYuJEFDPOLhoq3bFA     0  2015-04-28 20:31:58      0   
9994  ZCYCNWA98718SZ0A4bHD7A     0  2018-06-09 00:24:40      0   
9995  vdKUDXI1j89VO65Krg6VGg     0  2018-05-28 22:53:56      0   
9996  TxNeo206T0jMvRRQ4nKSIg     1  2013-01-02 21:09:13      1   
9997  4z_hAnw2UV5CzfcjtVvWsg     0  2017-11-18 21:07:11      0   
9998  ALUqFoEbPIXEwdX7QbyR_Q     0  2015-04-29 00:51:46  

In [0]:
x = df['text']
y = df['Predicted_review']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 101)

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv_transformer = CountVectorizer(analyzer = 'word')

In [0]:
x = cv_transformer.fit_transform(x)



In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 101)

In [0]:
from sklearn.naive_bayes import MultinomialNB

In [169]:
nb = MultinomialNB()
nb.fit(x_train, y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [170]:
predictions = nb.predict(x_test)
predictions

array(['Positive', 'Positive', 'Positive', ..., 'Neutral', 'Positive',
       'Positive'], dtype='<U8')

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [172]:
print(confusion_matrix(y_test, predictions))
print("\n")
print(classification_report(y_test, predictions))

[[   0   20   63]
 [   0   82  293]
 [  12  151 2379]]


              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        83
     Neutral       0.32      0.22      0.26       375
    Positive       0.87      0.94      0.90      2542

   micro avg       0.82      0.82      0.82      3000
   macro avg       0.40      0.38      0.39      3000
weighted avg       0.78      0.82      0.80      3000



In [173]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rmfr = RandomForestClassifier()
rmfr.fit(x_train,y_train)
predrmfr = rmfr.predict(x_test)
predrmfr

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Positive'], dtype=object)

In [174]:
print(confusion_matrix(y_test, predrmfr))
print("\n")
print(classification_report(y_test, predrmfr))

[[   6    1   76]
 [   1   22  352]
 [   1   25 2516]]


              precision    recall  f1-score   support

    Negative       0.75      0.07      0.13        83
     Neutral       0.46      0.06      0.10       375
    Positive       0.85      0.99      0.92      2542

   micro avg       0.85      0.85      0.85      3000
   macro avg       0.69      0.37      0.38      3000
weighted avg       0.80      0.85      0.79      3000



In [175]:
# Support Vector Machine
from sklearn.svm import SVC
svm = SVC(random_state=101)
svm.fit(x_train,y_train)
predsvm = svm.predict(x_test)
predsvm

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Positive'], dtype=object)

In [176]:
print(confusion_matrix(y_test, predsvm))
print("\n")
print(classification_report(y_test, predsvm))

[[   0    0   83]
 [   0    0  375]
 [   0    0 2542]]


              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        83
     Neutral       0.00      0.00      0.00       375
    Positive       0.85      1.00      0.92      2542

   micro avg       0.85      0.85      0.85      3000
   macro avg       0.28      0.33      0.31      3000
weighted avg       0.72      0.85      0.78      3000



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [177]:
# K Nearest Neighbour Algorithm
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train,y_train)
predknn = knn.predict(x_test)
predknn

array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Positive'], dtype=object)

In [178]:
print(confusion_matrix(y_test, predknn))
print("\n")
print(classification_report(y_test, predknn))

[[   0    0   83]
 [   0    5  370]
 [   0   11 2531]]


              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        83
     Neutral       0.31      0.01      0.03       375
    Positive       0.85      1.00      0.92      2542

   micro avg       0.85      0.85      0.85      3000
   macro avg       0.39      0.34      0.31      3000
weighted avg       0.76      0.85      0.78      3000



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [183]:

# Negative REVIEW
pr = df['text'][0]
print(pr)
print("Actual Rating: ",df['stars'][0])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])


total bill for this horrible service? over $8gs. these crooks actually had the nerve to charge us $69 for 3 pills. i checked online the pills can be had for 19 cents each! avoid hospital ers at all costs.
Actual Rating:  1.0
Predicted Rating: Negative


In [184]:
# Positive REVIEW
pr = df['text'][16]
print(pr)
print("Actual Rating: ",df['stars'][16])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:",nb.predict(pr_t)[0])


great lunch today. staff was very helpful in assisting with selections and knowledgeable on the ingredients. we enjoyed the bbq chicken with tika masala sauce and really good naan bread. the biryani with chicken was also yummy! fun to see the food being prepared in the tandoori ovens. great addition to the fast casual scene in cleveland.
Actual Rating:  4.0
Predicted Rating: Positive


In [185]:
# Misclassification REVIEW
pr = df['text'][42]
print(pr)
print("Actual Rating: ",df['stars'][42])
pr_t = cv_transformer.transform([pr])
print("Predicted Rating:", nb.predict(pr_t)[0])


i called the number provided and same day they showed up to my residence for an inspection. was able to advise me of multiple broken and loose tiles on my roof and came out just a few days later and completed the repairs. quoted me a good price for the repairs as well. no complaints!
Actual Rating:  5.0
Predicted Rating: Neutral
